config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  #authenticated routes
  authenticated :user do
    resources :babies do
      resources :activity_logs 
    end
    resources :assistants
    resources :activities
    root to: "babies#index"
  end
  #unauthenticated routes
  unauthenticated :user do
    resources :babies,only:[:index] do
      resources :activity_logs,only:[:index,:create,:update]
    end
    resources :activities,only:[:index]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/assistant.rb
# == Schema Information
#
# Table name: assistants
#
#  id         :integer          not null, primary key
#  address    :string(255)
#  group      :string(255)
#  name       :string(255)
#  phone      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Assistant < ApplicationRecord
	
  has_many :activities, through: :activity_logs
  has_many :babies, through: :activity_logs
  has_many :activity_logs

  validates :name,:address,:phone,presence:true

end

app/controllers/assistants_controller.rb
class AssistantsController < ApplicationController
  before_action :set_assistant, only: [:show, :edit, :update, :destroy]

  # GET /assistants
  # GET /assistants.json
  def index
    @assistants = Assistant.all
  end

  # GET /assistants/1
  # GET /assistants/1.json
  def show
  end

  # GET /assistants/new
  def new
    @assistant = Assistant.new
  end

  # GET /assistants/1/edit
  def edit
  end

  # POST /assistants
  # POST /assistants.json
  def create
    @assistant = Assistant.new(assistant_params)

    respond_to do |format|
      if @assistant.save
        format.html { redirect_to @assistant, notice: 'Assistant was successfully created.' }
        format.json { render :show, status: :created, location: @assistant }
      else
        format.html { render :new }
        format.json { render json: @assistant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assistants/1
  # PATCH/PUT /assistants/1.json
  def update
    respond_to do |format|
      if @assistant.update(assistant_params)
        format.html { redirect_to @assistant, notice: 'Assistant was successfully updated.' }
        format.json { render :show, status: :ok, location: @assistant }
      else
        format.html { render :edit }
        format.json { render json: @assistant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assistants/1
  # DELETE /assistants/1.json
  def destroy
    @assistant.destroy
    respond_to do |format|
      format.html { redirect_to assistants_url, notice: 'Assistant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assistant
      @assistant = Assistant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def assistant_params
      params.require(:assistant).permit(:name, :group, :address, :phone)
    end
end

app/helpers/assistants_helper.rb
module AssistantsHelper
end

app/views/assistants/_form.html.erb
<%= form_with(model: assistant, local: true) do |form| %>
  <% if assistant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(assistant.errors.count, "error") %> prohibited this assistant from being saved:</h2>

      <ul>
        <% assistant.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :group %>
    <%= form.text_field :group %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/assistants/edit.html.erb
<h1>Editing Assistant</h1>

<%= render 'form', assistant: @assistant %>

<%= link_to 'Show', @assistant %> |
<%= link_to 'Back', assistants_path %>

app/views/assistants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Assistants</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Group</th>
      <th>Address</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @assistants.each do |assistant| %>
      <tr>
        <td><%= assistant.name %></td>
        <td><%= assistant.group %></td>
        <td><%= assistant.address %></td>
        <td><%= assistant.phone %></td>
        <td><%= link_to 'Show', assistant %></td>
        <td><%= link_to 'Edit', edit_assistant_path(assistant) %></td>
        <td><%= link_to 'Destroy', assistant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Assistant', new_assistant_path %>

app/views/assistants/new.html.erb
<h1>New Assistant</h1>

<%= render 'form', assistant: @assistant %>

<%= link_to 'Back', assistants_path %>

app/views/assistants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @assistant.name %>
</p>

<p>
  <strong>Group:</strong>
  <%= @assistant.group %>
</p>

<p>
  <strong>Address:</strong>
  <%= @assistant.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @assistant.phone %>
</p>

<%= link_to 'Edit', edit_assistant_path(@assistant) %> |
<%= link_to 'Back', assistants_path %>