config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  #authenticated routes
  authenticated :user do
    resources :babies do
      resources :activity_logs 
    end
    resources :assistants
    resources :activities
    root to: "babies#index"
  end
  #unauthenticated routes
  unauthenticated :user do
    resources :babies,only:[:index] do
      resources :activity_logs,only:[:index,:create,:update]
    end
    resources :activities,only:[:index]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/activity_log.rb
# == Schema Information
#
# Table name: activity_logs
#
#  id           :integer          not null, primary key
#  comments     :text(65535)
#  duration     :integer
#  start_time   :datetime
#  stop_time    :datetime
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  activity_id  :integer
#  assistant_id :integer
#  baby_id      :integer
#
# Indexes
#
#  index_activity_logs_on_activity_id   (activity_id)
#  index_activity_logs_on_assistant_id  (assistant_id)
#  index_activity_logs_on_baby_id       (baby_id)
#
# Foreign Keys
#
#  fk_rails_...  (activity_id => activities.id)
#  fk_rails_...  (assistant_id => assistants.id)
#  fk_rails_...  (baby_id => babies.id)
#
class ActivityLog < ApplicationRecord
  belongs_to :baby
  belongs_to :assistant
  belongs_to :activity

  validates :comments,:duration, :stop_time,presence:true , on: :update
  validates :start_time,presence:true, on: :create

  #validate  start_time less to stop_time
  validate :stop_time_greater_than_start_time ,on: :update

  def default_duration
    self.duration ||= 0
  end
  
  #set duration of activity
  def set_duration
    time = stop_time - start_time
    time = (time / 1.minute).round
    self.update(duration: time)
  end

  #get the name of assistant
  def assistant_name
    assistant.name
  end

  #check if the activity was finalized
  def activity_finished_at
    time = stop_time - start_time if stop_time
    mins = (time / 1.minute).round if time
    mins == duration ? stop_time : stop_time = "En progreso" if mins
  end

  #config validation if start_time less to stop_time

  def stop_time_greater_than_start_time
    if  start_time > stop_time
      errors.add(:stop_time,"no puede ser menor a la fecha y hora de inicio ")
    end
  end

end

app/controllers/activity_logs_controller.rb
class ActivityLogsController < ApplicationController
  before_action :set_activity_log, only: [:show, :edit, :update, :destroy]
  before_action :set_baby
  # GET /activity_logs
  # GET /activity_logs.json
  def index
    @activity_logs = @baby.activity_logs.all.order(baby_id: :asc)
  end

  # GET /activity_logs/1
  # GET /activity_logs/1.json
  def show
  end

  # GET /activity_logs/new
  def new
    @activity_log = ActivityLog.new
  end

  # GET /activity_logs/1/edit
  def edit
  end

  # POST /activity_logs
  # POST /activity_logs.json
  def create
    
    @activity_log = @baby.activity_logs.new(activity_log_params)
    respond_to do |format|
      if @activity_log.save
        format.html { redirect_to baby_activity_logs_path, notice: 'Activity log was successfully created.' }
        format.json { render :index, status: :created, location: baby_activity_logs_path }
      else
        format.html { render :new }
        format.json { render json: @activity_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activity_logs/1
  # PATCH/PUT /activity_logs/1.json
  def update
    respond_to do |format|

      @activity_log.default_duration
      if @activity_log.update(activity_log_params)
         @activity_log.set_duration
        format.html { redirect_to @activity_log, notice: 'Activity log was successfully updated.' }
        format.json { render :index, status: :ok, location: baby_activity_logs_path }
      else
        format.html { render :edit }
        format.json { render json: @activity_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activity_logs/1
  # DELETE /activity_logs/1.json
  def destroy
    @activity_log.destroy
    respond_to do |format|
      format.html { redirect_to activity_logs_url, notice: 'Activity log was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity_log
      @activity_log = ActivityLog.find(params[:id])
    end
    def set_baby
      @baby = Baby.find(params[:baby_id])
    end

    # Only allow a list of trusted parameters through.
    def activity_log_params
      params.require(:activity_log).permit(:baby_id, :assistant_id, :activity_id, :start_time, :stop_time, :duration, :comments)
    end
end

app/helpers/activity_logs_helper.rb
module ActivityLogsHelper
end

app/views/activity_logs/_form.html.erb
<%= form_for [@baby, @activity_log]  do |form| %>
  <% if activity_log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(activity_log.errors.count, "error") %> prohibited this activity_log from being saved:</h2>

      <ul>
        <% activity_log.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :baby_id %>
    <%= form.text_field :baby_id %>
  </div>

  <div class="field">
    <%= form.label :assistant_id %>
    <%= form.text_field :assistant_id %>
  </div>

  <div class="field">
    <%= form.label :activity_id %>
    <%= form.text_field :activity_id %>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time %>
  </div>

  <div class="field">
    <%= form.label :stop_time %>
    <%= form.datetime_select :stop_time %>
  </div>

  <div class="field">
    <%= form.label :duration %>
    <%= form.number_field :duration %>
  </div>

  <div class="field">
    <%= form.label :comments %>
    <%= form.text_area :comments %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/activity_logs/edit.html.erb
<h1>Editing Activity Log</h1>

<%= render 'form', activity_log: @activity_log %>

app/views/activity_logs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Activity Logs</h1>

<table>
  <thead>
    <tr>
      <th>Baby</th>
      <th>Assistant</th>
      <th>Activity</th>
      <th>Start time</th>
      <th>Stop time</th>
      <th>Duration</th>
      <th>Comments</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @activity_logs.each do |activity_log| %>
      <tr>
        <td><%= activity_log.baby_id %></td>
        <td><%= activity_log.assistant.name %></td>
        <td><%= activity_log.activity_id %></td>
        <td><%= activity_log.start_time %></td>
        <td><%= activity_log.activity_finished_at%></td>
       
    
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/activity_logs/new.html.erb
<h1>New Activity Log</h1>

<%= render 'form', activity_log: @activity_log %>

app/views/activity_logs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Baby:</strong>
  <%= @activity_log.baby_id %>
</p>

<p>
  <strong>Assistant:</strong>
  <%= @activity_log.assistant_id %>
</p>

<p>
  <strong>Activity:</strong>
  <%= @activity_log.activity_id %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @activity_log.start_time %>
</p>

<p>
  <strong>Stop time:</strong>
  <%= @activity_log.stop_time %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @activity_log.duration %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @activity_log.comments %>
</p>

<%= link_to 'Edit', edit_activity_log_path(@activity_log) %> |
<%= link_to 'Back', activity_logs_path %>