config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  #authenticated routes
  authenticated :user do
    resources :babies do
      resources :activity_logs 
    end
    resources :assistants
    resources :activities
    root to: "babies#index"
  end
  #unauthenticated routes
  unauthenticated :user do
    resources :babies,only:[:index] do
      resources :activity_logs,only:[:index,:create,:update]
    end
    resources :activities,only:[:index]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/baby.rb
# == Schema Information
#
# Table name: babies
#
#  id          :integer          not null, primary key
#  address     :string(255)
#  birthday    :date
#  father_name :string(255)
#  mother_name :string(255)
#  name        :string(255)
#  phone       :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Baby < ApplicationRecord
  has_many :activity_logs
  has_many :activities, through: :activity_logs
  has_many :assistants, through: :activity_logs

  validates :address,:birthday,:father_name,:mother_name,:name,:phone,presence:true

  #get the age in months
  def age_in_months
    ((Time.zone.now - birthday.to_time) / 1.month).floor
  end
  
end

app/controllers/babies_controller.rb
class BabiesController < ApplicationController
  before_action :set_baby, only: [:show, :edit, :update, :destroy]

  # GET /babies
  # GET /babies.json
  def index
    @babies = Baby.all
    
  end

  # GET /babies/1
  # GET /babies/1.json
  def show


  end

  # GET /babies/new
  def new
    @baby = Baby.new
  end

  # GET /babies/1/edit
  def edit
  end

  # POST /babies
  # POST /babies.json
  def create
    @baby = Baby.new(baby_params)

    respond_to do |format|
      if @baby.save
        format.html { redirect_to @baby, notice: 'Baby was successfully created.' }
        format.json { render :show, status: :created, location: @baby }
      else
        format.html { render :new }
        format.json { render json: @baby.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /babies/1
  # PATCH/PUT /babies/1.json
  def update
    respond_to do |format|
      if @baby.update(baby_params)
        format.html { redirect_to @baby, notice: 'Baby was successfully updated.' }
        format.json { render :show, status: :ok, location: @baby }
      else
        format.html { render :edit }
        format.json { render json: @baby.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /babies/1
  # DELETE /babies/1.json
  def destroy
    @baby.destroy
    respond_to do |format|
      format.html { redirect_to babies_url, notice: 'Baby was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_baby
      @baby = Baby.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def baby_params
      params.require(:baby).permit(:name, :birthday, :mother_name, :father_name, :address, :phone)
    end
end

app/helpers/babies_helper.rb
module BabiesHelper
end

app/views/babies/_form.html.erb
<%= form_with(model: baby, local: true) do |form| %>
  <% if baby.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(baby.errors.count, "error") %> prohibited this baby from being saved:</h2>

      <ul>
        <% baby.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :birthday %>
    <%= form.date_select :birthday %>
  </div>

  <div class="field">
    <%= form.label :mother_name %>
    <%= form.text_field :mother_name %>
  </div>

  <div class="field">
    <%= form.label :father_name %>
    <%= form.text_field :father_name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/babies/edit.html.erb
<h1>Editing Baby</h1>

<%= render 'form', baby: @baby %>

<%= link_to 'Show', @baby %> |
<%= link_to 'Back', babies_path %>

app/views/babies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Babies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Months</th>
      <th>Mother name</th>
      <th>Father name</th>
      <th>Address</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @babies.each do |baby| %>
      <tr>
        <td><%= baby.name %></td>
        <td><%= baby.age_in_months %></td>
        <td><%= baby.mother_name %></td>
        <td><%= baby.father_name %></td>
        <td><%= baby.address %></td>
        <td><%= baby.phone %></td>
        <td><%= link_to 'Show', baby %></td>
        <td><%= link_to 'Edit', edit_baby_path(baby) %></td>
        <td><%= link_to 'Destroy', baby, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Baby', new_baby_path %>

app/views/babies/new.html.erb
<h1>New Baby</h1>

<%= render 'form', baby: @baby %>

<%= link_to 'Back', babies_path %>

app/views/babies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @baby.name %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @baby.birthday %>
</p>

<p>
  <strong>Mother name:</strong>
  <%= @baby.mother_name %>
</p>

<p>
  <strong>Father name:</strong>
  <%= @baby.father_name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @baby.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @baby.phone %>
</p>

<%= link_to 'Edit', edit_baby_path(@baby) %> |
<%= link_to 'Back', babies_path %>